themes:
  - name: "catppuccin-mocha"
    colors:
      - "#F5E0DC"  # Rosewater
      - "#F2CDCD"  # Flamingo
      - "#F5C2E7"  # Pink
      - "#CBA6F7"  # Mauve
      - "#F38BA8"  # Red
      - "#EBA0AC"  # Maroon
      - "#FAB387"  # Peach
      - "#F9E2AF"  # Yellow
      - "#A6E3A1"  # Green
      - "#94E2D5"  # Teal
      - "#89DCEB"  # Sky
      - "#74C7EC"  # Sapphire
      - "#89B4FA"  # Blue
      - "#B4BEFE"  # Lavender
      - "#CDD6F4"  # Text
      - "#BAC2DE"  # Subtext1
      - "#A6ADC8"  # Subtext0
      - "#9399B2"  # Overlay2
      - "#7F849C"  # Overlay1
      - "#6C7086"  # Overlay0
      - "#585B70"  # Surface2
      - "#45475A"  # Surface1
      - "#313244"  # Surface0
      - "#1E1E2E"  # Base
      - "#181825"  # Mantle
      - "#11111B"  # Crust
